### Updates an existing patient entity
PUT http://localhost:3000/patients
Content-Type: application/json

{
  "name": "Rohan Vishwakarma",
  "email": "rohanvishwakarma8261@gmail.com",
  "address": "Akhari Kurahua Varanasi",
  "dateOfBirth": "20005-08-04",
}
###